# Generated by Django 2.2.1 on 2019-09-27 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationConfiguration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('edited_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('code', models.CharField(max_length=250, unique=True)),
                ('value', models.CharField(blank=True, max_length=2000, null=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('type', models.CharField(max_length=250)),
                ('group_name', models.CharField(max_length=250)),
                ('sub_group_name', models.CharField(blank=True, max_length=250, null=True)),
                ('mutable', models.BooleanField()),
                ('sub_group_order', models.BigIntegerField(blank=True, null=True)),
                ('help', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appconf_created_by', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appconf_edited_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_configuration',
                'managed': True,
            },
        ),
    ]
