# Generated by Django 2.2.4 on 2020-01-14 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationConfiguration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('edited_date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('code', models.CharField(max_length=250, unique=True)),
                ('value', models.CharField(blank=True, max_length=2000, null=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('type', models.CharField(max_length=250)),
                ('group_name', models.CharField(max_length=250)),
                ('sub_group_name', models.CharField(blank=True, max_length=250, null=True)),
                ('mutable', models.BooleanField()),
                ('sub_group_order', models.BigIntegerField(blank=True, null=True)),
                ('help', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'application_configuration',
                'managed': True,
            },
        ),
    ]
