version: "3"

services:

  ozone_server:
    image: "ozone/server"
    build:
      context: "./"
    container_name: "ozone_server"
    ports:
      - "8080:8080"

  ozone_widgets:
    image: "ozone/widgets"
    build:
      context: "./ozone-example-widgets"
    container_name: "ozone_widgets"
    ports:
      - "4000:4000"
