version: '3'

services:

  ozone_client:
    image: ozone/client
    build:
      context: ./ozone-framework-client
    container_name: ozone_client
    volumes:
      - ./ozone-framework-client:/app
      - client_node_modules:/app/node_modules
    ports:
      - 3000:3000

  ozone_server:
    image: ozone/server
    build:
      context: ./ozone-framework-server
    container_name: ozone_server
    ports:
      - 8080:8080


volumes:
  client_node_modules:
