version: '3'

services:

  ozone_client:
    image: ozone/client
    build:
      context: ./ozone-framework-client
    container_name: ozone_client
    volumes:
      - ./ozone-framework-client:/app
      - ozone_client_node_modules:/app/node_modules
    ports:
      - 3000:3000

volumes:
  ozone_client_node_modules:
