version: "3"

services:

  ozone_client:
    image: "ozone/client"
    build:
      context: "./ozone-framework-client"
    container_name: "ozone_client"
    links:
      - "ozone_server:ozone_server"
    ports:
      - "3000:3000"
    environment:
      OZONE_API_SERVER_URL: "http://ozone_server:8080"

  ozone_widgets:
    image: "ozone/widgets"
    build:
      context: "./ozone-example-widgets"
    container_name: "ozone_widgets"
    ports:
      - "4000:4000"

  ozone_server:
    image: "ozone/server"
    build:
      context: "./ozone-framework-server"
    container_name: "ozone_server"
    ports:
      - "8080:8080"
