version: '3'

services:

  db:
    image: postgres
    container_name: "ozone_postgres"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - owf

  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: "ozone"
    entrypoint: /code/deploy-prod.sh
    environment:
      OWF_DB_HOST: 'db'
    ports:
      - "8000:8000"
    networks:
      - owf

  ozone_widgets:
    image: "ozone/widgets"
    build:
      context: "./ozone-example-widgets"
    container_name: "ozone_widgets"
    ports:
      - "4000:4000"
    networks:
      - owf

networks:
  owf:
    driver: bridge
