# Generated by Django 2.2.1 on 2019-08-15 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwfGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('status', models.CharField(max_length=8)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=200)),
                ('automatic', models.BooleanField()),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('stack_default', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'owf_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OwfGroupPeople',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='owf_groups.OwfGroup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owf_group_people',
                'managed': True,
                'unique_together': {('group', 'person')},
            },
        ),
    ]
