# Generated by Django 2.2.1 on 2019-08-26 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owf_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owfgrouppeople',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owf_groups.OwfGroup'),
        ),
        migrations.AlterField(
            model_name='owfgrouppeople',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
