# Generated by Django 2.2.1 on 2019-08-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owf_groups', '0002_auto_20190826_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owfgroup',
            name='stack_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='owfgroup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='owfgroup',
            name='version',
            field=models.BigIntegerField(default=0),
        ),
    ]
