# Generated by Django 2.2.1 on 2019-08-27 20:43

from django.db import migrations, models
import owf_groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('owf_groups', '0002_auto_20190826_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owfgroup',
            name='stack_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='owfgroup',
            name='status',
            field=models.CharField(choices=[(owf_groups.models.GroupStatus('active'), 'active'), (owf_groups.models.GroupStatus('inactive'), 'inactive')], default=owf_groups.models.GroupStatus('active'), max_length=8),
        ),
        migrations.AlterField(
            model_name='owfgroup',
            name='version',
            field=models.BigIntegerField(default=0),
        ),
    ]
