# Generated by Django 2.2.1 on 2019-11-13 05:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owf_groups', '0002_auto_20191113_0550'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='owfgrouppeople',
            name='unique_owfgroup_people',
        ),
        migrations.AlterUniqueTogether(
            name='owfgrouppeople',
            unique_together={('group', 'person')},
        ),
    ]
