# Generated by Django 2.2.1 on 2019-08-28 18:29

from django.db import migrations, models
import owf_groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('owf_groups', '0003_auto_20190828_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owfgroup',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='owfgroup',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default=owf_groups.models.GroupStatus('active'), max_length=8),
        ),
    ]
