# Generated by Django 2.2.1 on 2019-11-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owf_groups', '0003_auto_20191113_0556'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='owfgrouppeople',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='owfgrouppeople',
            constraint=models.UniqueConstraint(fields=('group', 'person'), name='unique_owfgroup_people'),
        ),
    ]
