# Generated by Django 2.2.1 on 2019-08-28 21:29

from django.conf import settings
from django.db import migrations, models
import owf_groups.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owf_groups', '0003_auto_20190828_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='owfgroup',
            name='people',
            field=models.ManyToManyField(through='owf_groups.OwfGroupPeople', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owfgroup',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default=owf_groups.models.GroupStatus('active'), max_length=8),
        ),
    ]
