# Generated by Django 2.2.1 on 2019-08-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owf_groups', '0005_auto_20190828_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owfgroup',
            name='automatic',
            field=models.BooleanField(default=True),
        ),
    ]
