# Generated by Django 2.2.1 on 2019-09-07 00:15

from django.conf import settings
from django.db import migrations, models
import django_enum_choices.choice_builders
import django_enum_choices.fields
import owf_groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('owf_groups', '0006_auto_20190829_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owfgroup',
            name='people',
            field=models.ManyToManyField(related_name='groups', through='owf_groups.OwfGroupPeople', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owfgroup',
            name='status',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('active', 'active'), ('inactive', 'inactive')], default=owf_groups.models.GroupStatus('active'), enum_class=owf_groups.models.GroupStatus, max_length=8),
        ),
    ]
