# Generated by Django 2.2.1 on 2019-12-03 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('value', models.TextField()),
                ('path', models.CharField(max_length=200)),
                ('namespace', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preference',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('path', 'namespace', 'user'), name='unique_path_namespace_user_preference'),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('path', 'namespace', 'user')},
        ),
    ]
