# Generated by Django 2.2.1 on 2019-11-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('path', 'namespace', 'user'), name='unique_path_namespace_user_preference'),
        ),
    ]
