# Generated by Django 2.2.1 on 2019-08-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField()),
                ('src_id', models.BigIntegerField()),
                ('src_type', models.CharField(max_length=255)),
                ('relationship_type', models.CharField(blank=True, max_length=8, null=True)),
                ('dest_id', models.BigIntegerField()),
                ('dest_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'domain_mapping',
                'managed': True,
            },
        ),
    ]
