# Generated by Django 2.2.1 on 2019-09-26 20:36

from django.db import migrations, models
import django_enum_choices.choice_builders
import django_enum_choices.fields
import domain_mappings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('src_id', models.BigIntegerField()),
                ('src_type', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('dashboard', 'dashboard'), ('group', 'group'), ('widget_definition', 'widget_definition')], enum_class=domain_mappings.models.MappingType, max_length=255)),
                ('relationship_type', django_enum_choices.fields.EnumChoiceField(blank=True, choice_builder=django_enum_choices.choice_builders.value_value, choices=[('owns', 'owns'), ('requires', 'requires'), ('instanceOf', 'instanceOf'), ('cloneOf', 'cloneOf')], default=domain_mappings.models.RelationshipType('owns'), enum_class=domain_mappings.models.RelationshipType, max_length=10, null=True)),
                ('dest_id', models.BigIntegerField()),
                ('dest_type', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('dashboard', 'dashboard'), ('group', 'group'), ('widget_definition', 'widget_definition')], enum_class=domain_mappings.models.MappingType, max_length=255)),
            ],
            options={
                'db_table': 'domain_mapping',
                'managed': True,
            },
        ),
    ]
