# Generated by Django 2.2.1 on 2019-08-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_mappings', '0002_auto_20190827_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmapping',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('owns', 'owns'), ('requires', 'requires'), ('instanceOf', 'instanceOf'), ('cloneOf', 'cloneOf')], default='owns', max_length=10, null=True),
        ),
    ]
