# Generated by Django 2.2.1 on 2019-09-07 00:15

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import domain_mappings.models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_mappings', '0003_auto_20190828_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmapping',
            name='dest_type',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Dashboard', 'Dashboard'), ('OwfGroup', 'OwfGroup')], enum_class=domain_mappings.models.MappingType, max_length=255),
        ),
        migrations.AlterField(
            model_name='domainmapping',
            name='relationship_type',
            field=django_enum_choices.fields.EnumChoiceField(blank=True, choice_builder=django_enum_choices.choice_builders.value_value, choices=[('owns', 'owns'), ('requires', 'requires'), ('instanceOf', 'instanceOf'), ('cloneOf', 'cloneOf')], default=domain_mappings.models.RelationshipType('owns'), enum_class=domain_mappings.models.RelationshipType, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='domainmapping',
            name='src_type',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Dashboard', 'Dashboard'), ('OwfGroup', 'OwfGroup')], enum_class=domain_mappings.models.MappingType, max_length=255),
        ),
    ]
