# Generated by Django 2.2.1 on 2019-09-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_mappings', '0004_auto_20190910_0941'),
        ('domain_mappings', '0004_auto_20190907_0015'),
    ]

    operations = [
    ]
