# Generated by Django 2.2.1 on 2019-09-13 21:39

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import domain_mappings.models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_mappings', '0005_merge_20190910_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmapping',
            name='dest_type',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('dashboard', 'dashboard'), ('group', 'group'), ('widget_definition', 'widget_definition')], enum_class=domain_mappings.models.MappingType, max_length=255),
        ),
        migrations.AlterField(
            model_name='domainmapping',
            name='src_type',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('dashboard', 'dashboard'), ('group', 'group'), ('widget_definition', 'widget_definition')], enum_class=domain_mappings.models.MappingType, max_length=255),
        ),
    ]
