include::../_variables.asciidoc[]

[#configuration]
= Configuration

OWF offers custom configuration options via the settings files used by Django, located in `config/settings`. Once changes are made, restart OWF to have the changes take effect.

The default settings provided in the `config/settings/production.py` file are intended for use in a local, non-production environment. For production deployment to a non-local environment or to use an external database, this file must be configured with the appropriate settings, which are explained throughout this guide.


=== Help settings

When a user clicks the question mark button in the toolbar, OWF offers online help:

Out of the bundle, the Help window contains:

* Instructions for Configuring Help

==== Changing the location of help files

The help directory location is defined by the `HELP_FILES` property in `{path-to-config}`.

By default, help files are located  in the `/config/staticfiles/` directory. In the default OWF bundle, this may be found at `{app-bundle}/`.

To change the directory location, replace `HELP_FILES` and then run 
`python manage.py collectstatic --settings=config.settings.production --no-input`

=== Custom Access Alert settings

Depending on the individual security requirements where OWF is being deployed, users may be required to agree to the specific terms of a security warning. 

Deploying a custom security warning requires modifications to one of the files in the client application and will require a re-build of the client application. Modifications will need to be made in the `messages.ts` file located in the `ozone-framework-client/packages/application/src/environment/` directory. Once the changes have been made, follow the instructions in the *Build Guide* to re-build and deploy the client application.
