# Generated by Django 2.2.1 on 2019-06-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetDefinition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=1)),
                ('width', models.IntegerField()),
                ('image_url_medium', models.CharField(max_length=2083)),
                ('singleton', models.BooleanField(default=False)),
                ('universal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(max_length=256)),
                ('widget_guid', models.CharField(max_length=255)),
                ('mobile_ready', models.BooleanField(default=False)),
                ('widget_version', models.CharField(blank=True, max_length=2083, null=True)),
                ('height', models.IntegerField()),
                ('background', models.BooleanField(default=False)),
                ('widget_url', models.CharField(max_length=2083)),
                ('image_url_small', models.CharField(max_length=2083)),
                ('descriptor_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'widget_definition',
            },
        ),
    ]
