# Generated by Django 2.2.1 on 2019-06-11 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetdefinition',
            name='height',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='widgetdefinition',
            name='widget_guid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='widgetdefinition',
            name='width',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
