# Generated by Django 2.2.1 on 2019-09-27 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('isdefault', models.BooleanField(blank=True, default=False)),
                ('dashboard_position', models.IntegerField(blank=True, default=0)),
                ('altered_by_admin', models.BooleanField(blank=True, default=False)),
                ('guid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('layout_config', models.TextField(blank=True, null=True)),
                ('locked', models.BooleanField(blank=True, default=False, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_image_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('published_to_store', models.BooleanField(blank=True, default=False, null=True)),
                ('marked_for_deletion', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_created_by', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_edited_by', to=settings.AUTH_USER_MODEL)),
                ('stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stacks.Stack')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard',
                'managed': True,
            },
        ),
    ]
