# Generated by Django 2.2.1 on 2019-08-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_auto_20190826_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='altered_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='dashboard_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='isdefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='marked_for_deletion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='published_to_store',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='version',
            field=models.BigIntegerField(default=0),
        ),
    ]
