# Generated by Django 2.2.1 on 2019-08-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20190827_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='altered_by_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='dashboard_position',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='isdefault',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
