# Generated by Django 2.2.1 on 2019-09-10 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_auto_20190828_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='dashboard_position',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
