# Generated by Django 2.2.1 on 2019-09-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_auto_20190907_0015'),
        ('dashboards', '0005_auto_20190910_0941'),
    ]

    operations = [
    ]
