# Generated by Django 2.2.1 on 2019-06-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=1)),
                ('owner_id', models.BigIntegerField(blank=True, null=True)),
                ('stack_context', models.CharField(max_length=200)),
                ('default_group_id', models.BigIntegerField(blank=True, null=True)),
                ('unique_widget_count', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('descriptor_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'stack',
            },
        ),
    ]
