# Generated by Django 2.2.1 on 2019-06-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owf_groups', '0002_auto_20190604_1622'),
        ('stacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owf_groups.OWFGroup')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.Stack')),
            ],
            options={
                'db_table': 'stack_groups',
            },
        ),
        migrations.AddField(
            model_name='stack',
            name='groups',
            field=models.ManyToManyField(through='stacks.StackGroup', to='owf_groups.OWFGroup'),
        ),
    ]
