# Generated by Django 2.2.1 on 2019-06-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190611_0524'),
        ('owf_groups', '0003_auto_20190611_0457'),
        ('stacks', '0002_auto_20190604_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='default_group_id',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='stack',
            name='default_group',
            field=models.ForeignKey(blank=True, db_column='default_group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_group', to='owf_groups.OWFGroup'),
        ),
        migrations.AddField(
            model_name='stack',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='stack',
            name='stack_context',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='stack',
            name='unique_widget_count',
            field=models.IntegerField(default=0),
        ),
    ]
