include::../../_variables.asciidoc[]

= Using Oracle

. Create an Oracle database user for OWF. It is recommended that there be a dedicated user for OWF to avoid database object name collisions. The OWF team recommends using UTF-8 encoding.

. Due to licensing issues, OWF does not provide a JDBC driver for Oracle. Obtain the appropriate JDBC driver and place it into the Web server's classpath. For example, if running Tomcat, the driver can be placed in the `{path-classpath}/` directory.

. Open the `{path-app-yml}` file and modify the `environments.production.dataSource` section using the values that are appropriate for the OWF environment.
+
[source,yaml]
.Example: application.yml
----
dataSource:
    pooled: true
    dbCreate: "none"
    username: "owf_user"
    password: "owf_password"
    dialect: "org.hibernate.dialect.Oracle10gDialect"
    driverClassName: "oracle.jdbc.driver.OracleDriver"
    url: "jdbc:oracle:thin:@myhost.somewhere.org:1521:DEVDB1"
    properties:
        minEvictableIdleTimeMillis: 180000
        timeBetweenEvictionRunsMillis: 180000
        numTestsPerEvictionRun: 3
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: true
        validationQuery: "SELECT 1 FROM DUAL"
----
+
In the example above, an Oracle database-user named `owf_user` with a password of `owf_password` is used for a database named `DEVDB1`.
+
There are several different types of Oracle drivers (thin, OCI, kprb) and connection options (service, SID, TNSName) available. Please consult the Oracle DBA and Oracle's JDBC documentation to create the connection most appropriate for the installed environment.

. To create the schema, run the `/dbscripts/oracle/OracleCreate.sql` script, prior to starting OWF.

. Ensure that the transaction is committed.


[discrete]
===== Notes:

* If running a production environment, no additional steps are necessary. However, if sample widgets are to be installed, `OraclePrefsUpdate_v7.14.0.sql` must be run prior to logging in. Logging in between the execution of these scripts can cause system failure.

* The OWF team is aware of a known issue with the Oracle Web-based Admin Console returning truncated characters when dealing with large data sets. Accordingly, using SQLPlus to run the script mentioned above is recommended.

* Old versions of the SQL scripts are included under `/database/archive`. These are included for the convenience of those upgrading from older versions of OWF.
