== Introduction

=== Objectives

The purpose of this guide is to explain how to use the Ozone Widget Framework (OWF). This is including, but not limited to, the use of application components, full applications and their configuration settings. This guide provides an introduction to the Ozone Widget Framework (OWF). OWF consists of an environment and a set of tools used for discovering, organizing and displaying Web applications in a single browser window. The guide explains how to use OWF, set up an OWF environment on a user's local machine, and navigate OWF security.

=== Document Scope

This guide is not an exhaustive reference. It is intended for users, developers and administrators seeking a quick introduction on how to deploy, start, and use OWF. For information about specific areas, see the relevant documentation included with the OWF bundle.

In this document, the terms Store and Marketplace are used interchangeably.

OWF runs on the Django framework and requires Python 3.7 or higher. By default, OWF will run using Waitress, a WSGI server. Waitress does not support TLS and a reverse proxy will be required, if a secure connection is desired. 


include::../../../common/related-documents.asciidoc[leveloffset=+2]
