== Allowing Remote Access to OWF

To run OWF remotely, and NOT from a localhost environment, execute the following steps:

. Identify a server host name.
. Generate a server certificate.
. Install the server certificate.
. Modify configuration files.

=== Identifying a Server Name

The server host name can be chosen arbitrarily and entered into the users' HOST files, or it can be obtained from DNS. This Quick Start Guide will refer to the selected server host name as `servername` and to OWF as `https://servername:port/owf/`.


=== Generate a Server Certificate

The certificates that ship with OWF are configured with a server host name of `localhost`. If the host name is changed, new certificates are required. The server certificate must reflect the selected host name.

Navigate to the `/etc/tools` folder and execute `create-certificates.bat` or `.sh`, depending on the operating system in use.

NOTE: Once this is done, the default user p12 certificates (`testUser1` and `testAdmin1`) will no longer be compatible. To correct this, create new user certificates using the create-certificates script.

Follow the prompts on screen and create the necessary certificates for the installation.


==== Install the Server Certificate

The OWF start script, located at `ozone/tomcat/bin/setenv.bat` (or `setenv.sh`) must be edited to point to the new keystore (defined while answering the prompts discussed in the previous section) file found in the `setenv` script.

Update the key store file name to reflect the new certificate.

.Example: setenv.sh
----
set CATALINA_OPTS=-Djavax.net.ssl.trustStore="%CATALINA_HOME%\certs\servername.jks"
  -Djavax.net.ssl.keyStore="%CATALINA_HOME%\certs\servername.jks"
  -Djavax.net.ssl.keyStorePassword=changeit -Djavax.net.ssl.trustStorePassword=changeit server
  -Xmx1024m -Xms512m -XX:PermSize=128m -XX:MaxPermSize=256m %JAVA_OPTS%
----

The Tomcat configuration file, located at `ozone/tomcat/conf/server.xml`, must also be edited to point to the new keystore file. This section can be found below the "Define a SSL…" section of the XML file:

.Example: server.xml
[source,xml]
----
<Connector port="8443"
           protocol="HTTP/1.1"
           scheme="https"
           secure="true"
           SSLEnabled="true"
           maxThreads="150"
           keystoreFile="certs/servername.jks"
           keystorePass="changeit"
           truststoreFile="certs/servername.jks"
           truststorePass="changeit"
           clientAuth="want"
           sslProtocol="TLS" />
----


=== Modify the Externalized Configuration Files

In order to access OWF from remote computers, externalized configuration files must point to the correct location.

Find the `owf.server.backendUrl` and `frontendUrl` properties in the `application.yml` file, and update the URLs with the new server host name.

.Example: application.yml
[source,yaml]
----
owf:
    server:
        backendUrl: "https://servername:8443/owf"
        frontendUrl: "https://servername:8443/owf"
----
