# Generated by Django 2.2.1 on 2019-06-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OWFGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=1)),
                ('stack_id', models.BigIntegerField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('stack_default', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=8)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('automatic', models.BooleanField()),
            ],
            options={
                'db_table': 'owf_group',
            },
        ),
    ]
