# Generated by Django 2.2.1 on 2019-06-11 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owf_groups', '0002_auto_20190604_1622'),
        ('stacks', '0002_auto_20190604_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owfgroup',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='owfgroup',
            name='stack_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='owfgroup',
            name='stack_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stacks.Stack'),
        ),
        migrations.AlterField(
            model_name='owfgroup',
            name='status',
            field=models.CharField(default='active', max_length=8),
        ),
    ]
