export const GET_STACKS_RESPONSE = {
    data: [
        {
            approved: true,
            imageUrl: "themes/common/images/admin/64x64_admin_app.png",
            owner: null,
            totalUsers: 0,
            totalGroups: 1,
            id: 67,
            groups: [
                {
                    stackDefault: false,
                    totalStacks: 0,
                    status: "active",
                    totalUsers: 0,
                    id: 23,
                    description: "OWF Administrators",
                    totalWidgets: 0,
                    email: null,
                    name: "OWF Administrators",
                    automatic: true,
                    displayName: "OWF Administrators"
                }
            ],
            stackContext: "ef8b5d6f-4b16-4743-9a57-31683c94b616",
            defaultGroup: {
                stackDefault: false,
                totalStacks: 0,
                status: "active",
                totalUsers: 0,
                id: 23,
                description: "OWF Administrators",
                totalWidgets: 0,
                email: null,
                name: "OWF Administrators",
                automatic: true,
                displayName: "OWF Administrators"
            },
            descriptorUrl: null,
            description:
                "This application collects the administrative components into a common set of application pages for managing system resources.  These pages can be used to create, modify, update, and delete Apps, App Components, Users and Groups, and system configuration settings.",
            totalWidgets: 0,
            name: "Administration",
            totalDashboards: 0
        },
        {
            approved: true,
            imageUrl: null,
            owner: null,
            totalUsers: 0,
            totalGroups: 1,
            id: 68,
            groups: [
                {
                    stackDefault: false,
                    totalStacks: 0,
                    status: "active",
                    totalUsers: 0,
                    id: 24,
                    description: "OWF Users",
                    totalWidgets: 0,
                    email: null,
                    name: "OWF Users",
                    automatic: true,
                    displayName: "OWF Users"
                }
            ],
            stackContext: "investments",
            defaultGroup: {
                stackDefault: false,
                totalStacks: 0,
                status: "active",
                totalUsers: 0,
                id: 24,
                description: "OWF Users",
                totalWidgets: 0,
                email: null,
                name: "OWF Users",
                automatic: true,
                displayName: "OWF Users"
            },
            descriptorUrl: null,
            description: "Sample app containing example investment pages.",
            totalWidgets: 0,
            name: "Investments",
            totalDashboards: 0
        },
        {
            approved: true,
            imageUrl: null,
            owner: null,
            totalUsers: 0,
            totalGroups: 1,
            id: 69,
            groups: [
                {
                    stackDefault: false,
                    totalStacks: 0,
                    status: "active",
                    totalUsers: 0,
                    id: 24,
                    description: "OWF Users",
                    totalWidgets: 0,
                    email: null,
                    name: "OWF Users",
                    automatic: true,
                    displayName: "OWF Users"
                }
            ],
            stackContext: "908d934d-9d53-406c-8143-90b406fb508f",
            defaultGroup: {
                stackDefault: false,
                totalStacks: 0,
                status: "active",
                totalUsers: 0,
                id: 24,
                description: "OWF Users",
                totalWidgets: 0,
                email: null,
                name: "OWF Users",
                automatic: true,
                displayName: "OWF Users"
            },
            descriptorUrl: null,
            description: null,
            totalWidgets: 0,
            name: "Sample",
            totalDashboards: 0
        },
        {
            approved: false,
            imageUrl: null,
            owner: {
                totalStacks: 0,
                hasPWD: null,
                totalGroups: 0,
                id: 26,
                userRealName: "Test User 1",
                totalWidgets: 0,
                username: "user",
                email: "user@goss.com",
                lastLogin: null,
                totalDashboards: 0
            },
            totalUsers: 0,
            totalGroups: 0,
            id: 14,
            groups: [],
            stackContext: "2e49c652-92d9-41ef-8ee7-e69f108ca082",
            defaultGroup: {
                stackDefault: true,
                totalStacks: 0,
                status: "active",
                totalUsers: 0,
                id: 13,
                description: "",
                totalWidgets: 0,
                email: null,
                name: "6fcf7419-a476-4c06-b41a-3feaf0d39c26",
                automatic: false,
                displayName: null
            },
            descriptorUrl: null,
            description: null,
            totalWidgets: 0,
            name: "Untitled",
            totalDashboards: 1
        },
        {
            approved: false,
            imageUrl: null,
            owner: {
                totalStacks: 0,
                hasPWD: null,
                totalGroups: 0,
                id: 26,
                userRealName: "Test User 1",
                totalWidgets: 0,
                username: "user",
                email: "user@goss.com",
                lastLogin: null,
                totalDashboards: 0
            },
            totalUsers: 0,
            totalGroups: 0,
            id: 36,
            groups: [],
            stackContext: "09100a72-7bf3-4016-ac1c-279023cd0b18",
            defaultGroup: {
                stackDefault: true,
                totalStacks: 0,
                status: "active",
                totalUsers: 0,
                id: 35,
                description: "",
                totalWidgets: 0,
                email: null,
                name: "2b2c51c2-388d-4784-8abb-e958b14989fc",
                automatic: false,
                displayName: null
            },
            descriptorUrl: null,
            description: null,
            totalWidgets: 0,
            name: "Untitled",
            totalDashboards: 1
        },
        {
            approved: false,
            imageUrl: null,
            owner: {
                totalStacks: 0,
                hasPWD: null,
                totalGroups: 0,
                id: 26,
                userRealName: "Test User 1",
                totalWidgets: 0,
                username: "user",
                email: "user@goss.com",
                lastLogin: null,
                totalDashboards: 0
            },
            totalUsers: 0,
            totalGroups: 0,
            id: 2,
            groups: [],
            stackContext: "70716b1d-246a-432e-a5f1-ee30ee715cb1",
            defaultGroup: {
                stackDefault: true,
                totalStacks: 0,
                status: "active",
                totalUsers: 0,
                id: 1,
                description: "",
                totalWidgets: 0,
                email: null,
                name: "4bf2e104-3376-4354-83c6-28e36baa825f",
                automatic: false,
                displayName: null
            },
            descriptorUrl: null,
            description: null,
            totalWidgets: 0,
            name: "Untitled",
            totalDashboards: 1
        },
        {
            approved: false,
            imageUrl: null,
            owner: {
                totalStacks: 0,
                hasPWD: null,
                totalGroups: 0,
                id: 26,
                userRealName: "Test User 1",
                totalWidgets: 0,
                username: "user",
                email: "user@goss.com",
                lastLogin: null,
                totalDashboards: 0
            },
            totalUsers: 0,
            totalGroups: 0,
            id: 8,
            groups: [],
            stackContext: "1efc8662-eea7-47b7-98b0-30cede37e462",
            defaultGroup: {
                stackDefault: true,
                totalStacks: 0,
                status: "active",
                totalUsers: 0,
                id: 7,
                description: "",
                totalWidgets: 0,
                email: null,
                name: "5096acfc-753c-49ee-879d-91bbe3e9ba24",
                automatic: false,
                displayName: null
            },
            descriptorUrl: null,
            description: null,
            totalWidgets: 0,
            name: "Untitled",
            totalDashboards: 1
        },
        {
            approved: false,
            imageUrl: null,
            owner: {
                totalStacks: 0,
                hasPWD: null,
                totalGroups: 0,
                id: 26,
                userRealName: "Test User 1",
                totalWidgets: 0,
                username: "user",
                email: "user@goss.com",
                lastLogin: null,
                totalDashboards: 0
            },
            totalUsers: 0,
            totalGroups: 0,
            id: 26,
            groups: [],
            stackContext: "80bf3809-298f-4d28-baaf-1d0279393d22",
            defaultGroup: {
                stackDefault: true,
                totalStacks: 0,
                status: "active",
                totalUsers: 0,
                id: 25,
                description: "",
                totalWidgets: 0,
                email: null,
                name: "9f8fde32-cd9d-4a43-a276-9d016d6eb39d",
                automatic: false,
                displayName: null
            },
            descriptorUrl: null,
            description: null,
            totalWidgets: 0,
            name: "Untitled",
            totalDashboards: 1
        },
        {
            approved: false,
            imageUrl: null,
            owner: {
                totalStacks: 0,
                hasPWD: null,
                totalGroups: 0,
                id: 26,
                userRealName: "Test User 1",
                totalWidgets: 0,
                username: "user",
                email: "user@goss.com",
                lastLogin: null,
                totalDashboards: 0
            },
            totalUsers: 0,
            totalGroups: 0,
            id: 20,
            groups: [],
            stackContext: "147af848-3ec2-4dac-945f-4c06cf5e51d5",
            defaultGroup: {
                stackDefault: true,
                totalStacks: 0,
                status: "active",
                totalUsers: 0,
                id: 19,
                description: "",
                totalWidgets: 0,
                email: null,
                name: "2140f7e9-4c34-40b1-bf8d-ae5756134b32",
                automatic: false,
                displayName: null
            },
            descriptorUrl: null,
            description: null,
            totalWidgets: 0,
            name: "Untitled",
            totalDashboards: 1
        }
    ],
    results: 9
};
