export const UPDATE_DASHBOARD_REQUEST = {
    _method: "PUT",
    name: "Untitled",
    description: "",
    iconImageUrl: "",
    guid: "80821b3b-b239-49b2-8b7d-b305ef40f717",
    isdefault: true,
    locked: false,
    state: [],
    layoutConfig: "",
    stack: "[object Object]",
    publishedToStore: true,
    bypassLayoutRearrange: true,
    version: "7.15.1-v1"
};

export const UPDATE_DASHBOARD_RESPONSE = {
    alteredByAdmin: "false",
    createdDate: "04/03/2019 12:32 PM EDT",
    isGroupDashboard: false,
    prettyCreatedDate: "12 minutes ago",
    isdefault: true,
    locked: false,
    dashboardPosition: 0,
    name: "Untitled",
    user: { userId: "admin" },
    type: null,
    EDashboardLayoutList: "[accordion, desktop, portal, tabbed]",
    layoutConfig:
        '{"xtype":"container","cls":"hbox ","layout":{"type":"hbox","align":"stretch"},"items":[{"xtype":"fitpane","cls":"left","htmlText":"48%","items":[],"widgets":[{"universalName":"org.owfgoss.owf.examples.ChannelListener","widgetGuid":"294587d6-8b6e-4b65-b6bb-d0a84100c2fc","uniqueId":"14d88004-02d8-2d62-e307-236a37d829e4","dashboardGuid":"80821b3b-b239-49b2-8b7d-b305ef40f717","paneGuid":"006d9778-4e7e-27ce-69e4-472f5a599a72","intentConfig":null,"launchData":null,"name":"Channel Listener","active":true,"x":0,"y":33,"zIndex":0,"minimized":false,"maximized":false,"pinned":false,"collapsed":false,"columnPos":0,"buttonId":null,"buttonOpened":false,"region":"none","statePosition":1,"singleton":false,"floatingWidget":false,"height":1215,"width":1227}],"paneType":"fitpane","flex":0.48,"defaultSettings":{}},{"xtype":"dashboardsplitter"},{"xtype":"container","cls":"vbox right","layout":{"type":"vbox","align":"stretch"},"items":[{"xtype":"tabbedpane","cls":"top","flex":1,"htmlText":"50%","items":[],"widgets":[],"paneType":"tabbedpane","defaultSettings":{}},{"xtype":"dashboardsplitter"},{"xtype":"accordionpane","cls":"bottom","flex":1,"htmlText":"50%","items":[],"paneType":"accordionpane","widgets":[],"defaultSettings":{}}],"flex":0.52,"htmlText":"52%"}],"flex":3}',
    createdBy: { userId: null, userRealName: null },
    stack: {
        approved: false,
        imageUrl: null,
        owner: {
            totalStacks: 0,
            hasPWD: null,
            totalGroups: 0,
            id: 1,
            userRealName: "Test Administrator 1",
            totalWidgets: 0,
            username: "admin",
            email: "admin@goss.com",
            lastLogin: null,
            totalDashboards: 0
        },
        totalUsers: 0,
        totalGroups: 0,
        id: 4,
        groups: [],
        stackContext: "e933b1a8-74b8-493a-aad0-c63349cb3c9e",
        defaultGroup: {
            stackDefault: true,
            totalStacks: 0,
            status: "active",
            totalUsers: 0,
            id: 3,
            description: "",
            totalWidgets: 0,
            email: null,
            name: "b0425edb-1967-49a0-99fa-f70ecb0c5a2f",
            automatic: false,
            displayName: null
        },
        descriptorUrl: null,
        description: null,
        totalWidgets: 0,
        name: "Untitled",
        totalDashboards: 0
    },
    publishedToStore: true,
    iconImageUrl: " ",
    editedDate: "04/03/2019 12:32 PM EDT",
    groups: [],
    prettyEditedDate: "12 minutes ago",
    description: " ",
    guid: "80821b3b-b239-49b2-8b7d-b305ef40f717",
    markedForDeletion: false
};
