# Generated by Django 2.2.1 on 2019-11-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stackgroups',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stackgroups',
            constraint=models.UniqueConstraint(fields=('group', 'stack'), name='unique_stack_groups'),
        ),
    ]
