# Generated by Django 2.2.1 on 2019-08-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owf_groups', '0004_auto_20190828_1429'),
        ('stacks', '0003_auto_20190827_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='groups',
            field=models.ManyToManyField(through='stacks.StackGroups', to='owf_groups.OwfGroup'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='default_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_stack_group', to='owf_groups.OwfGroup'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='stack_context',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='stack',
            name='version',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
