# Generated by Django 2.2.1 on 2019-09-10 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0004_auto_20190828_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='stack_context',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
