[#database-config]
= Database Configuration

While the full extent of administering databases is outside the scope of this guide, this section provides information on how to work with databases for OWF.

`application.yml` is a configuration file that allows an administrator to modify database connectivity information. It is located in the `{path-ozone}` directory. Once changes are made, restart OWF to apply them.

Listed below are the variable database elements that need to be modified to customize the OWF database. A detailed explanation of each field follows in <<database-properties>>.

[source,yaml]
.application.yml
----
dataSource:
    dbCreate: "none"
    username: "sa"
    password: ""
    driverClassName: "org.hsqldb.jdbcDriver"
    url: "jdbc:hsqldb:file:prodDb;shutdown=true"
    pooled: true
    properties:
        minEvictableIdleTimeMillis: 180000
        timeBetweenEvictionRunsMillis: 180000
        numTestsPerEvictionRun: 3
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: true
        validationQuery: "SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS"
----


include::installation/database-properties-table.asciidoc[]

NOTE: When setting up databases for OWF, be mindful of the database's lexical sorting mechanism. For some instances of OWF, with a small handful of users, this may not be much of an issue, but as the database becomes more populated, sorting may become increasingly difficult to manage.

include::installation/using-oracle.asciidoc[leveloffset=+1]

include::installation/using-mysql.asciidoc[leveloffset=+1]

include::installation/using-sql-server.asciidoc[leveloffset=+1]

