include::../_variables.asciidoc[]

[#upgrading]
= Upgrading


== Upgrading from version 7.17.1.0

. Before starting the upgrade, backup the corresponding database previously used with OWF 7.17.1.0 as well as all custom override configuration files (In Tomcat, they are normally located in the `/lib` directory)
+
For this upgrade, you can use your database used in OWF 7.17.1.0 with no alterations necessary. 
+
Please see <<configuration>> for any questions regarding configuration files.

. Install OWF
+
[subs="attributes"]
----
cp {file-bundle} /opt
cd /opt
unzip {file-bundle}
cd tomcat
----

. Make any configuration changes needed in `{file-app-yml}` configuration file, located in the bundle in the `{path-ozone}/` folder.
. Completing the upgrade
.. Reconfigure and re-apply customizations in the `/tomcat/lib` directory
.. If a custom keystore was deployed in a previous build, the keystore for OWF will need to be manually configured in the same manner.
.. Copy any custom certificates from previous build to {version-ozone}. Usually this is found in `/tomcat/certs`.
.. Upgrade is now complete


== Connecting to OMP (Marketplace)

In order to the connect your OMP Marketplace (v 7.17.X.X) with {version-ozone}, you must modify the following files:

* `application.properties`
** Make sure the following versions match the version numbers of the respective items in owf-framework-server.
[subs="attributes"]
+
----
app.base.version=8.0.0.0
tomcat.custom.rev=1.2.3-0
----

* `build.gradle`
** Make sure the following versions match the version numbers of the respective items in owf-framework-server.
+
----
mavenBom 'org.ozoneplatform:ozone-classic-bom:7.17.2-0'
customTomcat(group: 'org.ozoneplatform', name: 'owf-custom-tomcat', version: '1.2.3-0')
----

* `grails-app/conf/application.yml`
** Add URLs of all Ozone instances that will be using this store to the `allowedOrigins`, e.g.:
+
----
cors:
    allowedOrigins:
    - http://localhost:3000
    - https://192.168.1.2:8000

# Set the port for OMP to run on.
production:
    server:
        port: 8444
----

* `src/main/resources/ozone/marketplace/security.xml`
** Add URLs of all Ozone instances that will be using this store to the `allowedOrigins`, e.g.:
+
----
<sec:header name="Content-Security-Policy" value="frame-ancestors 
        http://localhost:3000/
        https://192.168.1.2:3000/
"/>
----

* Restart your application
* See Administration Guide on how to add stores to application


