# Generated by Django 2.2.1 on 2019-08-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetdefinitionwidgettypes',
            name='widget_definition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='widgets.WidgetDefinition'),
        ),
        migrations.AlterField(
            model_name='widgetdefinitionwidgettypes',
            name='widget_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.WidgetType'),
        ),
        migrations.AlterField(
            model_name='widgetdefintent',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intents.Intent'),
        ),
        migrations.AlterField(
            model_name='widgetdefintent',
            name='widget_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.WidgetDefinition'),
        ),
        migrations.AlterField(
            model_name='widgetdefintentdatatypes',
            name='intent_data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intents.IntentDataType'),
        ),
        migrations.AlterField(
            model_name='widgetdefintentdatatypes',
            name='widget_definition_intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.WidgetDefIntent'),
        ),
    ]
