# Generated by Django 2.2.1 on 2019-09-20 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_auto_20190827_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdefinition',
            name='types',
            field=models.ManyToManyField(related_name='widgets', through='widgets.WidgetDefinitionWidgetTypes', to='widgets.WidgetType'),
        ),
        migrations.AlterField(
            model_name='widgetdefinition',
            name='background',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='widgetdefinition',
            name='display_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='widgetdefinition',
            name='mobile_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='widgetdefinition',
            name='singleton',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='widgetdefinition',
            name='universal_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='widgetdefinition',
            name='version',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='widgetdefinition',
            name='widget_guid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
