---
grails:
    resources:
        # Enable browser caching for static assets (time in seconds) - sets 'Cache-Control' header 'max-age'
        cachePeriod: 600

---
security:
    basic:
        enabled: false

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

dataSource:
    pooled: true
    jmxExport: true

environments:
    test:
        dataSource:
            dbCreate: create-drop
            url: jdbc:jtds:sqlserver://localhost:1433/owf-test
            driverClassName: net.sourceforge.jtds.jdbc.Driver
            username: owf
            password: owf

    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:jtds:sqlserver://localhost:1433/owf-dev
            driverClassName: net.sourceforge.jtds.jdbc.Driver
            username: owf
            password: owf

    production:
        dataSource:
            dbCreate: update
            url: jdbc:jtds:sqlserver://localhost:1433/owf
            driverClassName: net.sourceforge.jtds.jdbc.Driver
            username: owf
            password: owf

            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
quartz:
    autoStartup: false
    jdbcStore: false

---
about:
    description: "<b>OZONE</b> is a framework for visually organizing and laying out lightweight web applications within a user's browser. Additionally, it provides infrastructure services to facilitate the development of analytic workflows and presentation tier application integration."
    # notice: "optional notice"

notifications:
    enabled: false
    query.interval: 30

owf:
    # log4j file watch interval in milliseconds
    log4jWatchTime: 180000  # 3 minutes

    sendWidgetLoadTimesToServer: true
    publishWidgetLoadTimes: true

    defaultTheme: "a_default"

    showAccessAlert: true
    accessAlertMsg: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla interdum eleifend sapien dignissim malesuada. Sed imperdiet augue vitae justo feugiat eget porta est blandit. Proin ipsum ipsum, rutrum ac gravida in, ullamcorper a augue. Sed at scelerisque augue. Morbi scelerisque gravida sapien ut feugiat. Donec dictum, nisl commodo dapibus pellentesque, enim quam consectetur quam, at dictum dui augue at risus. Ut id nunc in justo molestie semper. Curabitur magna velit, varius eu porttitor et, tempor pulvinar nulla. Nam at tellus nec felis tincidunt fringilla. Nunc nisi sem, egestas ut consequat eget, luctus et nisi. Nulla et lorem odio, vitae pretium ipsum. Integer tellus libero, molestie a feugiat a, imperdiet sit amet metus. Aenean auctor fringilla eros, sit amet suscipit felis eleifend a."

    # use to specify a logout url
    logoutURL: "/logout"

    # Sets the autoSave interval for saving dashboards in milliseconds
    autoSaveInterval: 900000  # 15 minutes

    helpFileRegex: '^.*\\.(htm|html|gsp|jsp|pdf|doc|docx|mov|mp4|wmv)$'

    # this value controls whether the OWF UI uses shims on floating elements, setting this to true will make
    # Applet/Flex have less zindex issues, but browser performance may suffer due to the additional shim frames being created
    useShims: false

    # Locations for the optional external themes and help directories.
    # Default: 'themes', 'help', and 'js-plugins' directories on the classpath.
    # Can be configured to an arbitrary file path.  The following
    # path styles are supported:
    #   'file:/some/absolute/path' ('file:C:/some/absolute/path' on Windows)
    #   'classpath:location/under/classpath'
    #   'location/within/OWF/war/file'
    # external:
    #    themePath:
    #    helpPath:
    #    jsPluginPath:

    exampleWidgets:
        enabled: true
        baseUrl: "widgets"

    metric:
        enabled: false
        url: 'https://localhost:8443/metric/metric'

        # Optional additional properties with default values shown
        #   keystorePath = System.properties['javax.net.ssl.keyStore']
        #   keystorePass = System.properties['javax.net.ssl.keyStorePassword']
        #   truststorePath = System.properties['javax.net.ssl.trustStore']
        #   timeout = 1800000

    dataguard:
        # Option to restrict messages between widgets based on access levels.
        # If this option is set to false, all other dataguard options are ignored.
        restrictMessages: false

        # Option to audit all messages between widgets, not just failed messages.
        # restrictMessages must be set to true
        auditAllMessages: false

        # Option to allow widgets to send messages without specifying their access level.
        # restrictMessages must be set to true
        allowMessagesWithoutAccessLevel: true

        # The amount of time (in milliseconds) to cache a widget's access level.
        # restrictMessages must be set to true
        accessLevelCacheTimeout: 3600000

    # OZP-476: Marketplace (MP) Synchronization
    mpSync:
        # Process listing change notifications from Marketplace(s)
        enabled: false

        # Change notification from MP will cause a new widget to be createdin OWF if it does not already exist
        autoCreateWidget: false
