# Generated by Django 2.2.1 on 2019-08-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentdatatypes',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intents.Intent'),
        ),
        migrations.AlterField(
            model_name='intentdatatypes',
            name='intent_data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intents.IntentDataType'),
        ),
    ]
