# Generated by Django 2.2.1 on 2019-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='types',
            field=models.ManyToManyField(related_name='intents', through='intents.IntentDataTypes', to='intents.IntentDataType'),
        ),
    ]
