# Generated by Django 2.2.1 on 2019-08-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intents', '0002_auto_20190826_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='version',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='intentdatatype',
            name='version',
            field=models.BigIntegerField(default=0),
        ),
    ]
