version: '3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    depends_on:
      - pgadmin

  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /code/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - postgres
    depends_on:
      - db

  # Postgres Admin Interface
  # http://localhost:5555
  # How to connect to New Postgres server
  # Add new server
  # Required Fields
  ## General
  ### Name: Postgres Django
  ## Connection
  ### Host      db
  ### Port      5432
  ### Username  postgres
  ### Password  postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@goss.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5555:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge