# Generated by Django 2.2.1 on 2019-10-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personwidgetdefinition',
            name='user_widget',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
