# Generated by Django 2.2.4 on 2019-12-11 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_notification',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='prev_login',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
