# Generated by Django 2.2.4 on 2019-12-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20191211_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
