# Generated by Django 2.2.1 on 2019-09-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190827_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personwidgetdefinition',
            name='group_widget',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personwidgetdefinition',
            name='user_widget',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='personwidgetdefinition',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='personwidgetdefinition',
            constraint=models.UniqueConstraint(fields=('person', 'widget_definition'), name='unique_person_widget_definition'),
        ),
    ]
