# Generated by Django 2.2.1 on 2019-09-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190911_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personwidgetdefinition',
            name='pwd_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personwidgetdefinition',
            name='version',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='personwidgetdefinition',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
