# Generated by Django 2.2.1 on 2019-06-03 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=1)),
                ('user_real_name', models.CharField(max_length=200)),
                ('last_notification', models.DateTimeField(blank=True, null=True)),
                ('requires_sync', models.BooleanField(default=False)),
                ('prev_login', models.DateTimeField(blank=True, null=True)),
                ('email_show', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
