# Generated by Django 2.2.1 on 2019-06-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
        ('people', '0002_auto_20190603_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonWidgetDefinition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=1)),
                ('pwd_position', models.IntegerField()),
                ('favorite', models.BooleanField(blank=True, null=True)),
                ('user_widget', models.BooleanField(blank=True, null=True)),
                ('disabled', models.BooleanField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=256, null=True)),
                ('group_widget', models.BooleanField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
                ('widget_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.WidgetDefinition')),
            ],
            options={
                'db_table': 'person_widget_definition',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='widget_definitions',
            field=models.ManyToManyField(through='people.PersonWidgetDefinition', to='widgets.WidgetDefinition'),
        ),
    ]
