# Generated by Django 2.2.1 on 2019-06-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190604_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personwidgetdefinition',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personwidgetdefinition',
            name='favorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personwidgetdefinition',
            name='group_widget',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personwidgetdefinition',
            name='user_widget',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personwidgetdefinition',
            name='widget_definition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='widgets.WidgetDefinition'),
        ),
    ]
