databaseChangeLog:

  - changeSet:
      id: 7.17.0-application_configuration
      author: owf
      comment: create application_configuration table
      dbms: postgresql

      preConditions:
        - onFail: MARK_RAN
        - not:
            - tableExists:
                tableName: application_configuration
                schemaName: ${schema.name}

      changes:
        - createTable:
            tableName: application_configuration
            schemaName: ${schema.name}

            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                      nullable: false
                      primaryKey: true
                      primaryKeyName: application_configurationPK
              - column:
                  name: version
                  type: bigint
                  defaultValue: '0'
                  constraints:
                      nullable: false
              - column:
                  name: created_by_id
                  type: bigint
                  constraints:
                      references: person (id)
                      foreignKeyName: FKFC9C0477666C6D2
              - column:
                  name: created_date
                  type: date
              - column:
                  name: edited_by_id
                  type: bigint
                  constraints:
                      references: person (id)
                      foreignKeyName: FKFC9C047E31CB353
              - column:
                  name: edited_date
                  type: date
              - column:
                  name: code
                  type: varchar(250)
                  constraints:
                      nullable: false
                      unique: true
                      uniqueKeyName: application_configuration_code_key
              - column:
                  name: VALUE
                  type: varchar(2000)
              - column:
                  name: title
                  type: varchar(250)
                  constraints:
                      nullable: false
              - column:
                  name: description
                  type: varchar(2000)
              - column:
                  name: type
                  type: varchar(250)
                  constraints:
                      nullable: false
              - column:
                  name: group_name
                  type: varchar(250)
                  constraints:
                      nullable: false
              - column:
                  name: sub_group_name
                  type: varchar(250)
              - column:
                  name: mutable
                  type: boolean
                  constraints:
                      nullable: false
              - column:
                  name: sub_group_order
                  type: bigint
              - column:
                  name: help
                  type: varchar(2000)
        - createIndex:
            tableName: application_configuration
            schemaName: ${schema.name}
            columns:
              - column:
                  name: group_name
                  type: varchar(255)
            indexName: app_config_group_name_idx
        - createIndex:
            tableName: application_configuration
            schemaName: ${schema.name}
            columns:
              - column:
                  name: created_by_id
            indexName: fkfc9c0477666c6d2
        - createIndex:
            tableName: application_configuration
            schemaName: ${schema.name}
            columns:
              - column:
                  name: edited_by_id
            indexName: fkfc9c047e31cb353

  - changeSet:
      id: 7.17.0-application_configuration
      author: owf
      comment: create application_configuration table
      dbms: mysql

      preConditions:
        - onFail: MARK_RAN
        - not:
            - tableExists:
                tableName: application_configuration
                schemaName: ${schema.name}

      changes:
        - createTable:
            tableName: application_configuration
            schemaName: ${schema.name}

            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                      nullable: false
                      primaryKey: true
                      primaryKeyName: application_configuration_pkey
              - column:
                  name: version
                  type: bigint
                  defaultValue: '0'
                  constraints:
                      nullable: false
              - column:
                  name: created_by_id
                  type: bigint
                  constraints:
                      references: person (id)
                      foreignKeyName: FKFC9C0477666C6D2
              - column:
                  name: created_date
                  type: date
              - column:
                  name: edited_by_id
                  type: bigint
                  constraints:
                      references: person (id)
                      foreignKeyName: FKFC9C047E31CB353
              - column:
                  name: edited_date
                  type: date
              - column:
                  name: code
                  type: varchar(250)
                  constraints:
                      nullable: false
                      unique: true
                      uniqueKeyName: code
              - column:
                  name: VALUE
                  type: varchar(2000)
              - column:
                  name: title
                  type: varchar(250)
                  constraints:
                      nullable: false
              - column:
                  name: description
                  type: varchar(2000)
              - column:
                  name: type
                  type: varchar(250)
                  constraints:
                      nullable: false
              - column:
                  name: group_name
                  type: varchar(250)
                  constraints:
                      nullable: false
              - column:
                  name: sub_group_name
                  type: varchar(250)
              - column:
                  name: mutable
                  type: tinyint(1)
                  constraints:
                      nullable: false
              - column:
                  name: sub_group_order
                  type: bigint
              - column:
                  name: help
                  type: varchar(2000)
        - createIndex:
            tableName: application_configuration
            schemaName: ${schema.name}
            columns:
              - column:
                  name: group_name
                  type: varchar(255)
            indexName: app_config_group_name_idx

  - changeSet:
      id: 7.17.0-application_configuration
      author: owf
      comment: create application_configuration table
      dbms: oracle

      preConditions:
        - onFail: MARK_RAN
        - not:
            - tableExists:
                tableName: application_configuration
                schemaName: ${schema.name}

      changes:
        - createTable:
            tableName: application_configuration
            schemaName: ${schema.name}

            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                      nullable: false
                      primaryKey: true
                      primaryKeyName: application_configurationPK
              - column:
                  name: version
                  type: bigint
                  defaultValue: '0'
                  constraints:
                      nullable: false
              - column:
                  name: created_by_id
                  type: bigint
                  constraints:
                      references: person (id)
                      foreignKeyName: FKFC9C0477666C6D2
              - column:
                  name: created_date
                  type: date
              - column:
                  name: edited_by_id
                  type: bigint
                  constraints:
                      references: person (id)
                      foreignKeyName: FKFC9C047E31CB353
              - column:
                  name: edited_date
                  type: date
              - column:
                  name: code
                  type: varchar(250)
                  constraints:
                      nullable: false
                      unique: true
                      uniqueConstraintName: SYS_C007485
              - column:
                  name: VALUE
                  type: varchar(2000)
              - column:
                  name: title
                  type: varchar(250)
                  constraints:
                      nullable: false
              - column:
                  name: description
                  type: varchar(2000)
              - column:
                  name: type
                  type: varchar(250)
                  constraints:
                      nullable: false
              - column:
                  name: group_name
                  type: varchar(250)
                  constraints:
                      nullable: false
              - column:
                  name: sub_group_name
                  type: varchar(250)
              - column:
                  name: mutable
                  type: boolean
                  constraints:
                      nullable: false
              - column:
                  name: sub_group_order
                  type: bigint
              - column:
                  name: help
                  type: varchar(2000)
        - createIndex:
            tableName: application_configuration
            schemaName: ${schema.name}
            columns:
              - column:
                  name: group_name
                  type: varchar(255)
            indexName: APP_CONFIG_GROUP_NAME_IDX
        - createIndex:
            tableName: application_configuration
            schemaName: ${schema.name}
            columns:
              - column:
                  name: created_by_id
            indexName: fkfc9c0477666c6d2
        - createIndex:
            tableName: application_configuration
            schemaName: ${schema.name}
            columns:
              - column:
                  name: edited_by_id
            indexName: fkfc9c047e31cb353

  - changeSet:
      id: 7.17.0-application_configuration
      author: owf
      comment: create application_configuration table
      dbms: mssql

      preConditions:
        - onFail: MARK_RAN
        - not:
            - tableExists:
                tableName: application_configuration
                schemaName: ${schema.name}

      changes:
        - createTable:
            tableName: application_configuration
            schemaName: ${schema.name}

            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                      nullable: false
                      primaryKey: true
                      primaryKeyName: application_configurationPK
              - column:
                  name: version
                  type: bigint
                  defaultValue: '0'
                  constraints:
                      nullable: false
              - column:
                  name: created_by_id
                  type: number(19, 0)
                  constraints:
                      references: person (id)
                      foreignKeyName: FKFC9C0477666C6D2
              - column:
                  name: created_date
                  type: smalldatetime
              - column:
                  name: edited_by_id
                  type: number(19,0)
                  constraints:
                      references: person (id)
                      foreignKeyName: FKFC9C047E31CB353
              - column:
                  name: edited_date
                  type: smalldatetime
              - column:
                  name: code
                  type: varchar(250)
                  constraints:
                      nullable: false
                      unique: true
                      uniqueKeyName: application_configuration_code_key
              - column:
                  name: VALUE
                  type: varchar(2000)
              - column:
                  name: title
                  type: varchar(250)
                  constraints:
                      nullable: false
              - column:
                  name: description
                  type: varchar(2000)
              - column:
                  name: type
                  type: varchar(250)
                  constraints:
                      nullable: false
              - column:
                  name: group_name
                  type: varchar(250)
                  constraints:
                      nullable: false
              - column:
                  name: sub_group_name
                  type: varchar(250)
              - column:
                  name: mutable
                  type: boolean
                  constraints:
                      nullable: false
              - column:
                  name: sub_group_order
                  type: bigint
              - column:
                  name: help
                  type: varchar(2000)
        - createIndex:
            tableName: application_configuration
            schemaName: ${schema.name}
            columns:
              - column:
                  name: group_name
                  type: varchar(255)
            indexName: app_config_group_name_idx
        - createIndex:
            tableName: application_configuration
            schemaName: ${schema.name}
            columns:
              - column:
                  name: created_by_id
            indexName: FKFC9C0477666C6D2
        - createIndex:
            tableName: application_configuration
            schemaName: ${schema.name}
            columns:
              - column:
                  name: edited_by_id
            indexName: FKFC9C047E31CB353